name: Retrain Model

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow==2.5.0 pandas scikit-learn matplotlib seaborn joblib

      - name: List files for debugging
        run: |
          echo "Current directory:"
          pwd
          echo "Files in repository:"
          ls -la
          echo "MLProject directory:"
          ls -la MLProject/ || echo "MLProject directory not found"

      - name: Run MLflow Project
        run: |
          # Gunakan env-manager=local sebagai pengganti --no-conda
          mlflow run . --env-manager=local

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: |
            mlruns/
            artifacts/
            *.png
            *.txt